language: node_js
matrix:
  include:
    - node_js: node
      env: BUILD=TEST
    - node_js: node
      env: 
        - BUILD=DOCS ENCRYPTION_LABEL=a668d2a97a80 COMMIT_AUTHOR_EMAIL=bcrit001@ucr.edu

script:
  - if [ "$BUILD" = "TEST" ]; then npm test; fi
#  - if [ "$BUILD" = "DOCS" ]; then ./deploy.sh; fi
