language: node_js
node_js:
  - stable

matrix:
  include:
    - node_js: stable
      env: BUILD=TEST
    - node_js: stable
      env: 
        - BUILD=DOCS ENCRYPTION_LABEL=a668d2a97a80 COMMIT_AUTHOR_EMAIL=mbrad012@ucr.edu

script:
  - if [ "$BUILD" = "TEST" ]; then npm test; fi
  - if [ "$BUILD" = "DOCS" ]; then ./deploy.sh; fi
